site_name: F333's Personal Docs
theme:
  name: material
  logo: assets/logo.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: "light green"
      accent: "lime"
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue
      accent: deep orange

  icon:
    logo: material/book
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.select
    - content.code.annotate

docs_dir: src
site_dir: docs

nav:
  - Home: index.md
  - Life:
      - Software:
          - "Manga App e Software": "Software e App/manga.md"
      - Problemi Isola: "isola.md"
  - Dev:
      - Server e Backend:
          - "Django, Postgrest, Nginx e Gunicorn": "Backend/Django, Postgrest, Nginx e Gunicorn.md"
          - "Errori comuni Django": "Backend/Errori comuni Django.md"
          - "Nginx Server con Fail2Ban": "Backend/Nginx Server con Fail2Ban.md"
          - "Altri casi non mappati": "Backend/Altro.md"
          - "FTP server": "Backend/FTP.md"
      - Esempi:
          - "Python e Google": "Esempi/Google implementation.md"

markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - abbr

  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search:
      lang: it
  - tags
  - minify:
      minify_html: true
  - open-in-new-tab
