site_name: F333's Personal Docs
theme:
  name: material
  favicon: assets/logo.png
  logo: assets/logo.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: "light green"
      accent: "lime"
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue
      accent: deep orange

  icon:
    logo: material/book

docs_dir: src
site_dir: docs

nav:
  - Home: index.md
  - Life:
      - Software:
          - "Manga App e Software": "Software e App/manga.md"
      - Problemi Isola: "isola.md"
      - Games:
          - "Monster Hunter Wild": "Games/Monster Hunter Wild.md"
  - Dev:
      - Server e Backend:
          - "Django, Postgrest, Nginx e Gunicorn": "Backend/Django, Postgrest, Nginx e Gunicorn.md"
          - "Errori comuni Django": "Backend/Errori comuni Django.md"
          - "Nginx Server con Fail2Ban": "Backend/Nginx Server con Fail2Ban.md"
          - "FTP server": "Backend/FTP.md"
          - "Altri casi non mappati": "Backend/Altro.md"
      - Sviluppo:
          - "Python Coding": "Dev/Python.md"
      - Esempi e Snippets:
          - "Python e Google": "Esempi/Google implementation.md"
          - "Snippets": "Esempi/Snippets.md"
